name = "Planet Origins"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50b8a3335bb1e7e07baad034d59fd39aaec1df96454822b69b0f4083d41e15b1"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
