name = "Planet Origins"
author = "Lith"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a7a0befa23a20ba6075da0a5089d7f460b8f3d80d5039ca58e9284c6289f276"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
