name = "Planet Origins"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf2bc825c1e7048dbf3efe1df2461e094498c1ad31f5543a9cbaa34394781c42"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
