name = "Planet Origins"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "084b1873d9ee06ceb1ea83d03d2bad9bccd1f8fdaa09b8fa919a48a7ec743bb0"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
