name = "Planet Origins"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61cd70758634cc4212768383c2b713ceacbf61d76cc7d241547cdd33da880e75"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
