name = "Planet Origins"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b8605d5dfeb5aca2eede65f6c6cbe57d2a169be197d7171115e078fb3f4252e"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
