name = "Planet Origins"
author = "Lith"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1d81f21af2476640a96b72f2abe6be0f801870e443c7e120c062c130fdcf3d0"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
