name = "Planet Origins"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f873c99e47d2e005ebf4511a104852391e4387a7a8a9f7c4b9d24277a5b8c430"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
