name = "Planet Origins"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4604461e01c7f28025ee1a02959fcdb2932d60bdab9673447a111f908e717ca"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
