name = "Planet Origins"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc6a72e621d204d7da8560ccefd12bf47e44f617eaf028a140f356b1b043fe65"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
