name = "Planet Origins"
author = "Lith"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "068a87f8c462c30a56e56fc5756bfd8c146acbfcc3a2be7b99ad41f93a751ff6"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
