name = "Planet Origins"
author = "Lith"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "080acbf43b9be46f01081ac5b28eb0e930491e5f5a9c882cdf507e8de9377d2b"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
