name = "Planet Origins"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0aa96dbcf46b124a1dd09e2d2e5a10dcfebfa09398a9e335abe34bc6fc6c33a6"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
