name = "Planet Origins"
author = "Lith"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afd84b55242ee7cc2eaa00d6a5a84f44d7b4dc4130ffdfb18b6f3bdeae507b6c"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
