name = "Planet Origins"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1346d2e16bba2925add6a39dd647f800bcae7ee295e33ad9dfbf4d38f0663f1"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
