name = "Planet Origins"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a612c09f53059cf69d7f5e599aee401e100b317b2055fc588a2600a0ebefa74a"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
