name = "Planet Origins"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83283d51c39b754aa07fbe9e05b660dd2e6efabfe8082aaae20af46d77f65038"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
