name = "Planet Origins"
author = "Lith"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f01dd8e3fca47cd7a0e602860175ca76d7aebdbf963f3a22e91d02b81aadfa3b"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
