name = "Planet Origins"
author = "Lith"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb9b79c54a4d84dcd463c1dfdc5a8b8c2a0b0f82054d3dfbb335e6d8a5ad121d"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
