name = "Planet Origins"
author = "Lith"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b0f5dc3466fa482dddb3e9dd33714d320a8728c3eb2162a7acf52ee4f126adf"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
