name = "Planet Origins"
author = "Lith"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "621c845ec1506be7ee4577e52bee158a3c72ceadad734f2407f1bca36cc634bb"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
