name = "Planet Origins"
author = "Lith"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32e5cc9394e8bb11d68c25352fe7a08103845f85ab9e974c379bc16295c936db"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
