name = "Cinderscapes"
filename = "cinderscapes-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/696/cinderscapes-1.4.0.jar"
hash-format = "murmur2"
hash = "4152586680"

[update]
[update.curseforge]
file-id = 3424696
project-id = 391429
release-channel = "beta"
