name = "ConnectedTexturesMod for Fabric"
filename = "ctm-fabric-0.5.1+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3416/753/ctm-fabric-0.5.1+1.16.jar"
hash-format = "murmur2"
hash = "524965872"

[update]
[update.curseforge]
file-id = 3416753
project-id = 432493
release-channel = "beta"
