name = "Origins"
filename = "Origins-1.16.5-0.7.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3319/81/Origins-1.16.5-0.7.3.jar"
hash-format = "murmur2"
hash = "3070985783"

[update]
[update.curseforge]
file-id = 3319081
project-id = 391943
release-channel = "beta"
