name = "Pehkui"
filename = "Pehkui-2.3.0+1.14.4-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3419/524/Pehkui-2.3.0+1.14.4-1.17.1.jar"
hash-format = "murmur2"
hash = "3786322900"

[update]
[update.curseforge]
file-id = 3419524
project-id = 319596
release-channel = "beta"
