name = "Recipe Cache"
filename = "recipecache-0.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3281/223/recipecache-0.1.0.jar"
hash-format = "murmur2"
hash = "1966621948"

[update]
[update.curseforge]
file-id = 3281223
project-id = 473492
release-channel = "beta"
