name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.11.5_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3367/437/Xaeros_Minimap_21.11.5_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "2781459048"

[update]
[update.curseforge]
file-id = 3367437
project-id = 263420
release-channel = "beta"
