name = "Xaero's World Map"
filename = "XaerosWorldMap_1.17.0_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3443/617/XaerosWorldMap_1.17.0_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "1840790706"

[update]
[update.curseforge]
file-id = 3443617
project-id = 317780
release-channel = "beta"

[option]
optional = true
description = "Adds a minimap. Xearos minimap needed. MINIMAPS MAY CAUSE A PERFORMANCE LOSS"